## 11-1 Series
(1)Series 创建

In [1]:
import pandas as pd
import numpy as np

# 从列表创建Series
series1 = pd.Series([1, 2, 3])
print(series1)

# 从字典创建Series
data_dict = {'a': 1, 'b': 2, 'c': 3}
series2 = pd.Series(data_dict)
print(series2)

# 从NumPy数组创建Series
array_data = np.array([10, 20, 30])
series3 = pd.Series(array_data)
print(series3)

0    1
1    2
2    3
dtype: int64
a    1
b    2
c    3
dtype: int64
0    10
1    20
2    30
dtype: int64

（2）Series 基本属性与操作

In [2]:
# 查看数据类型
series4 = pd.Series([5, 6, 7, 8, 9, 10])
print(series4.dtype)

# 获取统计信息
print(series4.describe())

# 访问关键属性
print(series4.values)  # 获取数据部分
print(series4.index)   # 获取索引
print(series4.name)    # 获取Series名称（默认None）

int64
count     6.000000
mean      7.500000
std       1.870829
min       5.000000
25%       6.250000
50%       7.500000
75%       8.750000
max      10.000000
dtype: float64
[ 5  6  7  8  9 10]
RangeIndex(start=0, stop=6, step=1)
None

（3）Series 索引和切片

In [3]:
# 位置索引
print(series4[0])

5

In [4]:
# 标签索引（基于字典创建的series2）
print(series2['a'])

1

In [5]:
# 位置切片（不包含结束位置）
print(series4[1:4])

1    6
2    7
3    8
dtype: int64

In [6]:
# 标签切片（包含结束标签）
print(series2['a':'c'])

a    1
b    2
c    3
dtype: int64

In [7]:
# 布尔索引
print(series4[series4 > 3])

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

## 11-2 DataFrame
（1）DataFrame 创建

In [8]:
# 从字典创建DataFrame
data_dict = {
    '姓名': ['张伟', '王芳', '李娜'],
    '年龄': [25, 30, 35],
    '城市': ['北京', '上海', '广州']
}
df = pd.DataFrame(data_dict)
print(df)

   姓名  年龄  城市
0  张伟  25  北京
1  王芳  30  上海
2  李娜  35  广州

In [9]:
# 从嵌套列表创建DataFrame（指定列名）
data_list = [['张伟', 25, '北京'], 
             ['王芳', 30, '上海'], 
             ['李娜', 35, '广州']]
df2 = pd.DataFrame(data_list, columns=['姓名', '年龄', '城市'])
print(df2)

   姓名  年龄  城市
0  张伟  25  北京
1  王芳  30  上海
2  李娜  35  广州

（2）DataFrame 基本属性与操作

In [10]:
# 查看维度（行数、列数）
print(df.shape)

(3, 3)

In [11]:
# 查看列标签
print(df.columns)

Index(['姓名', '年龄', '城市'], dtype='object')

In [12]:
# 查看行索引
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [13]:
# 查看每列数据类型
print(df.dtypes)

姓名    object
年龄     int64
城市    object
dtype: object

In [14]:
# 查看前2行数据
print(df.head(2))

   姓名  年龄  城市
0  张伟  25  北京
1  王芳  30  上海

In [15]:
# 获取数值列统计信息
print(df.describe())

         年龄
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

（3）DataFrame 索引和切片

In [16]:
# 按列标签访问列
print(df['姓名'])

0    张伟
1    王芳
2    李娜
Name: 姓名, dtype: object

In [17]:
# loc方法（基于标签索引）
print(df.loc[0, '姓名'])

张伟

In [18]:
# iloc方法（基于位置索引）
print(df.iloc[0, 1])

25

In [19]:
#iloc方法（切片）
print(df.iloc[1:3, :])

   姓名  年龄  城市
1  王芳  30  上海
2  李娜  35  广州

（4）DataFrame 行列操作

In [20]:
# 添加新行（使用concat）
new_row = pd.Series({'姓名': '赵磊', '年龄': 40, '城市': '深圳'})
df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
print(df)

   姓名  年龄  城市
0  张伟  25  北京
1  王芳  30  上海
2  李娜  35  广州
3  赵磊  40  深圳

In [21]:
# 添加新列
df['性别'] = ['男', '女', '女', '男']
print(df)

   姓名  年龄  城市 性别
0  张伟  25  北京  男
1  王芳  30  上海  女
2  李娜  35  广州  女
3  赵磊  40  深圳  男

In [22]:
# 删除指定行（原地修改）
df.drop(index=0, inplace=True)
print(df)

   姓名  年龄  城市 性别
1  王芳  30  上海  女
2  李娜  35  广州  女
3  赵磊  40  深圳  男

In [23]:
# 删除指定列（原地修改）
df.drop(columns=['年龄'], inplace=True)
print(df)

   姓名  城市 性别
1  王芳  上海  女
2  李娜  广州  女
3  赵磊  深圳  男

## 11-3 数据导入与导出
（1）数据导入

In [24]:
# 读取CSV文件
df_csv = pd.read_csv('GDP.csv')
print(df_csv.head(3))

            指标     2017年     2018年     2019年      2020年
0    国民总收入(亿元)  830945.7  915243.5  983751.2  1008782.5
1   国内生产总值(亿元)  832035.9  919281.1  986515.2  1015986.2
2  第一产业增加值(亿元)   62099.5   64745.2   70473.6    77754.1

In [25]:
# 读取Excel文件（指定工作表）
df_excel = pd.read_excel('data.xlsx', sheet_name='Sheet1')
print(df_excel.head())

   姓名  城市 性别
0  王芳  上海  女
1  李娜  广州  女
2  赵磊  深圳  男

In [26]:
# 读取JSON文件
df_json = pd.read_json('data.json')
print(df_json.head())

   姓名  城市 性别
1  王芳  上海  女
2  李娜  广州  女
3  赵磊  深圳  男

In [27]:
import sqlite3

# 读取SQLite数据库
conn = sqlite3.connect('database.db')
df_sql = pd.read_sql('SELECT * FROM tablename', conn)
print(df_sql.head())
conn.close()

   姓名  城市 性别
0  王芳  上海  女
1  李娜  广州  女
2  赵磊  深圳  男

（2）数据导出

In [28]:
# 导出为CSV文件（不含行索引）
df.to_csv('output.csv', index=False)

In [29]:
# 导出为Excel文件（指定工作表，不含行索引）
df.to_excel('output.xlsx', sheet_name='Sheet1', index=False)

In [30]:
# 导出为JSON文件
df.to_json('output.json')

In [31]:
# 导出到SQLite数据库
conn = sqlite3.connect('database.db')
df.to_sql('tablename', conn, if_exists='replace', index=False)
conn.close()

## 11-4 数据清洗
（1）缺失数据处理

In [32]:
import pandas as pd

# 创建含缺失值的DataFrame
data = {'姓名': ['张伟', '李娜', '王芳', None],
        '年龄': [25, None, 30, 35],
        '城市': ['北京', '上海', None, '广州']}
df = pd.DataFrame(data)

# 检测缺失值
print(df.isna())

      姓名     年龄     城市
0  False  False  False
1  False   True  False
2  False  False   True
3   True  False  False

In [33]:
# 统计每列缺失值数量
print(df.isna().sum())

姓名    1
年龄    1
城市    1
dtype: int64

In [34]:
# 用平均值填充年龄列缺失值
df['年龄'] = df['年龄'].fillna(value=df['年龄'].mean())

# 前向填充城市列缺失值
df['城市'] = df['城市'].fillna(method='ffill')

# 后向填充城市列缺失值（替换前向填充）
df['城市'] = df['城市'].fillna(method='bfill')

# 删除含缺失值的行
df_dropped = df.dropna()

# 删除含缺失值的列
df_dropped_cols = df.dropna(axis=1)

C:\Users\xh_z\AppData\Local\Temp\ipykernel_36440\3968422815.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['城市'] = df['城市'].fillna(method='ffill')
C:\Users\xh_z\AppData\Local\Temp\ipykernel_36440\3968422815.py:8: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['城市'] = df['城市'].fillna(method='bfill')

（2）数据过滤与选择

In [35]:
# 筛选出年龄大于30的人员
filtered_df = df[df['年龄'] > 30]
print(filtered_df)

     姓名    年龄  城市
3  None  35.0  广州

In [36]:
# 筛选出年龄大于 30 且居住在 '北京' 的人员
filtered_df_multi = df[(df['年龄'] > 30) & (df['城市'] == '北京')]
print(filtered_df_multi)

Empty DataFrame
Columns: [姓名, 年龄, 城市]
Index: []

In [37]:
# query方法筛选（数学>80且英语>75）
data_student = {'姓名': ['张伟', '李娜', '王芳', '赵磊'],
                '数学': [85, 78, 92, 88],
                '英语': [80, 72, 95, 89]}
df_student = pd.DataFrame(data_student)
result_query1 = df_student.query("数学 > 80 and 英语 > 75")
print(result_query1)

   姓名  数学  英语
0  张伟  85  80
2  王芳  92  95
3  赵磊  88  89

In [38]:
# query方法使用动态变量
math_threshold = 85
result_query2 = df_student.query("数学 > @math_threshold")
print(result_query2)

   姓名  数学  英语
2  王芳  92  95
3  赵磊  88  89

In [39]:
# query方法字符串筛选（姓名包含"张"）
result_query3 = df_student.query("姓名.str.contains('张')", engine='python')
print(result_query3)

   姓名  数学  英语
0  张伟  85  80

（3）数据转换
数据类型转换astype()方法

In [40]:
 # 年龄列转为整数
df['年龄'] = df['年龄'].astype(int)

删除重复数据drop_duplicates() 方法

In [41]:
# 删除重复行（保留第一行）
df_unique = df.drop_duplicates()

# 删除重复行（保留最后一行）
df_unique_last = df.drop_duplicates(keep='last')

# 按指定列判断重复行并删除
df_unique_subset = df.drop_duplicates(subset=['姓名'])

字符串操作与处理str

In [42]:
# 字符串操作（去除空白、替换字符）
df['城市'] = df['城市'].str.strip()
df['城市'] = df['城市'].str.replace('北京', 'Beijing')

## 11-5 数据分析与操作
（1）数据排序与索引
根据列值排序sort_values()方法

In [43]:
import pandas as pd

# 创建示例DataFrame
data = {'姓名': ['张伟', '李娜', '王芳', '赵磊'],
        '年龄': [25, 30, 35, 40],
        '城市': ['北京', '上海', '广州', '深圳']}
df = pd.DataFrame(data)

# 按年龄升序排序
df_sorted = df.sort_values(by='年龄')
print(df_sorted)

   姓名  年龄  城市
0  张伟  25  北京
1  李娜  30  上海
2  王芳  35  广州
3  赵磊  40  深圳

In [44]:
# 多列排序（先按城市，再按年龄）
df_sorted = df.sort_values(by=['城市', '年龄'])
print(df_sorted)

   姓名  年龄  城市
1  李娜  30  上海
0  张伟  25  北京
2  王芳  35  广州
3  赵磊  40  深圳

根据索引排序sort_index()方法

In [45]:
# 按列索引排序
df_sorted_cols = df.sort_index(axis=1)
print(df_sorted_cols)

   城市  姓名  年龄
0  北京  张伟  25
1  上海  李娜  30
2  广州  王芳  35
3  深圳  赵磊  40

设置索引set_index()方法

In [46]:
# 设置姓名列为索引
df_indexed = df.set_index('姓名')
print(df_indexed)

    年龄  城市
姓名
张伟  25  北京
李娜  30  上海
王芳  35  广州
赵磊  40  深圳

重置索引reset_index()方法

In [47]:
# 重置为默认整数索引
df_reset = df_indexed.reset_index()
print(df_reset)

   姓名  年龄  城市
0  张伟  25  北京
1  李娜  30  上海
2  王芳  35  广州
3  赵磊  40  深圳

（2）数据分组与聚合

分组操作groupby() 方法

In [48]:
# 创建示例DataFrame
data = {'姓名': ['张伟', '李娜', '王芳', '赵磊', '陈刚', '刘敏'],
        '年龄': [28, 30, 32, 40, 25, 35],
        '城市': ['北京', '上海', '广州', '深圳', '北京', '广州']}
df = pd.DataFrame(data)

# 按城市分组
grouped = df.groupby('城市')

print(grouped)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001EF10753620>

聚合函数与分析

接上例，计算每个城市的平均年龄，并更改列名为 '平均年龄'

In [49]:
# 计算每个城市的平均年龄（重命名列）
mean_age = grouped['年龄'].mean().rename('平均年龄')
print(mean_age)

城市
上海    30.0
北京    26.5
广州    33.5
深圳    40.0
Name: 平均年龄, dtype: float64

接上例，计算每个城市的人员数量，并更改列名为 '人数'

In [50]:
# 计算每个城市的人员数量（重命名列）
count_people = grouped['姓名'].count().rename('人数')
print(count_people)

城市
上海    1
北京    2
广州    2
深圳    1
Name: 人数, dtype: int64

In [51]:
# agg 方法：对DataFrame的列进行聚合操作
# ===================== 1：准备模拟销售数据 =====================
# 构造包含门店、日期、销量、单价的销售数据表（新手易理解的业务场景）
sales_data = {
    "门店": ["A店", "A店", "B店", "B店", "A店", "B店", "C店", "C店"],
    "日期": ["2026-01-01", "2026-01-02", "2026-01-01", "2026-01-02", 
            "2026-01-03", "2026-01-03", "2026-01-01", "2026-01-02"],
    "销量": [50, 65, 30, 45, 70, 55, 20, 35],
    "单价": [10.5, 10.5, 12.0, 12.0, 10.5, 12.0, 15.0, 15.0]
}
df = pd.DataFrame(sales_data)
df

   门店          日期  销量    单价
0  A店  2026-01-01  50  10.5
1  A店  2026-01-02  65  10.5
2  B店  2026-01-01  30  12.0
3  B店  2026-01-02  45  12.0
4  A店  2026-01-03  70  10.5
5  B店  2026-01-03  55  12.0
6  C店  2026-01-01  20  15.0
7  C店  2026-01-02  35  15.0

In [52]:
# ===================== 1: 多函数聚合 =====================
# 对指定列（销量）同时执行多个聚合函数（求和、均值、最大值、最小值）
# 方式1：列表形式指定多函数
agg_multi_1 = df["销量"].agg(["sum", "mean", "max", "min"])
# 方式2：对多列执行多函数（销量、单价都执行sum和mean）
agg_multi_2 = df[["销量", "单价"]].agg(["sum", "mean"])

# ===================== 2. 按列指定不同聚合函数 =====================
# 核心场景：不同列需要不同的聚合逻辑（比如销量求和，单价求均值和最大值）
# 用字典指定：key=列名，value=聚合函数（单个/多个）
agg_col_spec = df.agg({
    "销量": "sum",          # 销量列：求和
    "单价": ["mean", "max"] # 单价列：求均值+最大值
})

# ===================== 3. 结合分组 + 按列指定聚合 =====================
# 实战高频场景：先按门店分组，再对每组的销量/单价执行不同聚合
group_agg = df.groupby("门店").agg({
    "销量": ["sum", "mean"],  # 每组销量：求和+均值
    "单价": "max"             # 每组单价：求最大值
})

# ===================== 4. 自定义聚合函数 =====================
# 场景：内置函数满足不了需求时，自定义聚合函数（比如求“极差=最大值-最小值”）
# 自定义函数1：求极差
def range_func(x):
    """计算序列的极差（max - min）"""
    return x.max() - x.min()

# 自定义函数2：求中位数绝对偏差（MAD）
def mad_func(x):
    """计算中位数绝对偏差（可理解为“数据离散程度”的指标）"""
    median = x.median()
    return (x - median).abs().median()

# 应用自定义函数
agg_custom = df.agg({
    "销量": [range_func, mad_func],
    "单价": range_func
})

In [53]:
print("=== 1. 多函数聚合：对单列执行多个函数 ===")
print(agg_multi_1)
print("\n=== 对多列执行多个函数 ===")
print(agg_multi_2)
print("\n" + "="*50 + "\n")

print("=== 2. 按列指定不同聚合函数 ===")
print(agg_col_spec)
print("\n" + "="*50 + "\n")

print("=== 3. 分组+agg：按门店分组后，按列指定聚合函数 ===")
print(group_agg)
print("\n" + "="*50 + "\n")

print("=== 4. 自定义聚合函数 ===")
print("销量极差 = 销量最大值 - 销量最小值")
print("单价极差 = 单价最大值 - 单价最小值")
print("销量MAD = 销量的中位数绝对偏差（离散程度指标）")
print(agg_custom)

=== 1. 多函数聚合：对单列执行多个函数 ===
sum     370.00
mean     46.25
max      70.00
min      20.00
Name: 销量, dtype: float64

=== 对多列执行多个函数 ===
          销量       单价
sum   370.00  97.5000
mean   46.25  12.1875

==================================================

=== 2. 按列指定不同聚合函数 ===
         销量       单价
sum   370.0      NaN
mean    NaN  12.1875
max     NaN  15.0000

==================================================

=== 3. 分组+agg：按门店分组后，按列指定聚合函数 ===
     销量               单价
    sum       mean   max
门店
A店  185  61.666667  10.5
B店  130  43.333333  12.0
C店   55  27.500000  15.0

==================================================

=== 4. 自定义聚合函数 ===
销量极差 = 销量最大值 - 销量最小值
单价极差 = 单价最大值 - 单价最小值
销量MAD = 销量的中位数绝对偏差（离散程度指标）
              销量   单价
range_func  50.0  4.5
mad_func    15.0  NaN

（3）数据合并
基于键的合并merge() 方法

In [54]:
# merge方法（按姓名内连接）
df1 = pd.DataFrame({'姓名': ['张伟', '李娜', '王芳'], '年龄': [25, 30, 35]})
df2 = pd.DataFrame({'姓名': ['张伟', '李娜', '赵磊'], '城市': ['北京', '上海', '深圳']})
merged_df = pd.merge(df1, df2, on='姓名', how='inner')
print(merged_df)

   姓名  年龄  城市
0  张伟  25  北京
1  李娜  30  上海

基于索引的合并 join() 方法

In [55]:
# join方法（按索引左连接）
df1_indexed = pd.DataFrame({'年龄': [25, 30, 35]}, index=['张伟', '李娜', '王芳'])
df2_indexed = pd.DataFrame({'城市': ['北京', '上海', '深圳']}, index=['张伟', '李娜', '赵磊'])
joined_df = df1_indexed.join(df2_indexed, how='left')
print(joined_df)

    年龄   城市
张伟  25   北京
李娜  30   上海
王芳  35  NaN

直接拼接concat() 方法

In [56]:
# concat方法（按行拼接）
df3 = pd.DataFrame({'姓名': ['张伟', '李娜'], '年龄': [25, 30]})
df4 = pd.DataFrame({'姓名': ['王芳'], '年龄': [35]})
concatenated_df_row = pd.concat([df3, df4], axis=0, ignore_index=True)
print(concatenated_df_row)

# concat方法（按列拼接）
df5 = pd.DataFrame({'姓名': ['张伟', '李娜']})
df6 = pd.DataFrame({'城市': ['北京', '上海']})
concatenated_df_col = pd.concat([df5, df6], axis=1)
print(concatenated_df_col)

   姓名  年龄
0  张伟  25
1  李娜  30
2  王芳  35
   姓名  城市
0  张伟  北京
1  李娜  上海

（4）数据重塑

数据透视表pivot_table() 方法

例  使用数据透视表汇总中国城市和商品类别的销售数据

In [57]:
data_pivot = {
    '城市': ['北京', '北京', '上海', '上海', '广州', '广州', '深圳', '深圳', '北京', '上海'],
    '商品类别': ['电子产品', '家具', '电子产品', '家具', '电子产品', '家具', '电子产品', '家具', '家具', '电子产品'],
    '销售额': [500, 300, 700, 450, 400, 320, 600, 410, 200, 300]
}
df_pivot = pd.DataFrame(data_pivot)
print(df_pivot)

   城市  商品类别  销售额
0  北京  电子产品  500
1  北京    家具  300
2  上海  电子产品  700
3  上海    家具  450
4  广州  电子产品  400
5  广州    家具  320
6  深圳  电子产品  600
7  深圳    家具  410
8  北京    家具  200
9  上海  电子产品  300

In [58]:
pivot_table = df_pivot.pivot_table(values='销售额', index='城市', columns='商品类别', aggfunc='sum')
print(pivot_table)

商品类别   家具  电子产品
城市
上海    450  1000
北京    500   500
广州    320   400
深圳    410   600

数据展开melt() 方法

例  将宽格式的城市和商品类别销售数据展开为长格式

In [59]:
# melt（数据展开，宽格式转长格式）
data_melt = {
    '城市': ['北京', '上海', '广州', '深圳'],
    '电子产品': [500, 700, 400, 600],
    '家具': [300, 450, 320, 410]
}
df_melt = pd.DataFrame(data_melt)
print(df_melt)

   城市  电子产品   家具
0  北京   500  300
1  上海   700  450
2  广州   400  320
3  深圳   600  410

In [60]:
melted_df = pd.melt(df_melt, id_vars=['城市'], var_name='商品类别', value_name='销售额')
print(melted_df)

   城市  商品类别  销售额
0  北京  电子产品  500
1  上海  电子产品  700
2  广州  电子产品  400
3  深圳  电子产品  600
4  北京    家具  300
5  上海    家具  450
6  广州    家具  320
7  深圳    家具  410

In [61]:
import pandas as pd
import string
import random  # 用于生成随机的字母出现次数

# ===================== 步骤1：准备基础数据 =====================
# 1. 生成26个英文字母（a-z）作为完整的字母表
alphabet = list(string.ascii_lowercase)  # ['a','b','c',...,'z']
# 2. 定义文档数量（这里设为5个文档，可自行调整）
doc_num = 100
# 3. 合成“文档ID-字母-出现次数”数据
synthetic_data = []
random.seed(42)

for doc_id in range(1, doc_num + 1):
    # 为每个文档随机选择若干字母（3-8个，模拟文档内容）
    selected_letters = random.sample(alphabet, random.randint(3, 8))
    # 为每个选中的字母随机生成出现次数（1-5次）
    for letter in selected_letters:
        count = random.randint(1, 5)
        synthetic_data.append({
            "doc_id": doc_id,
            "letter": letter,
            "count": count
        })

# 转换成DataFrame（pivot_table的输入格式）
letter_doc_df = pd.DataFrame(synthetic_data)
letter_doc_df

     doc_id letter  count
0         1      d      5
1         1      a      1
2         1      x      5
3         1      i      4
4         1      h      1
..      ...    ...    ...
569     100      x      4
570     100      y      1
571     100      w      5
572     100      e      3
573     100      d      2

[574 rows x 3 columns]

In [62]:
# ===================== 步骤2：用pivot_table构造词袋向量 =====================
# 核心：将纵向的“letter”列旋转为横向列，覆盖全部26个字母
bow_vector = letter_doc_df.pivot_table(
    index="doc_id",          # 行：文档ID（每个文档对应一行向量）
    columns="letter",        # 列：26个英文字母（纵向转横向）
    values="count",          # 单元格值：字母在文档中的出现次数
    fill_value=0,            # 未出现的字母填充0（词袋向量核心要求）
    dropna=False             # 强制保留全部26个字母列（即使某字母未出现）
).reindex(columns=alphabet)  # 确保列的顺序是a-z（随机生成后列可能乱序，整理更易读）

# ===================== 步骤3：输出结果 =====================
# print("=== 合成的文档-字母-出现次数数据（前10行）===")
# print(letter_doc_df.head(10))
# print("\n=== 最终的26字母词袋向量（每行是1个文档的向量）===")
display(bow_vector)

letter,a,b,c,d,e,f,g,h,i,j,...,q,r,s,t,u,v,w,x,y,z
doc_id,,,,,,,,,,,,,,,,,,,,,
1,1.0,0.0,0.0,5.0,1.0,0.0,0.0,1.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,2.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,4.0,5.0,0.0,0.0,0.0,0.0
97,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.0,5.0,0.0,0.0,4.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,...,0.0,0.0,2.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0
100,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,5.0,4.0,1.0,0.0

## 案例：员工信息数据集清洗与整理
假设有一份员工信息数据集，其中包含姓名、年龄、职位、工资等基本信息。由于数据来源复杂，可能存在缺失值、重复数据和格式不一致等问题。

（1）数据准备

In [63]:
import pandas as pd
import numpy as np

# （1）数据准备
data = {
    '姓名': ['张伟', '李娜', '王强', '刘洋', '张伟', None, '陈敏', '赵磊', '杨杰'],
    '年龄': [25, np.nan, 35, 45, 25, 30, np.nan, 55, 60],
    '职位': ['经理', '开发', '开发工程师', '设计', '经理', '经理', '设计师', None, '开发'],
    '工资': [70000, 80000, np.nan, 75000, 70000, 85000, 72000, 90000, np.nan]
}
df = pd.DataFrame(data)
print("原始数据集：")
print(df)

原始数据集：
     姓名    年龄     职位       工资
0    张伟  25.0     经理  70000.0
1    李娜   NaN     开发  80000.0
2    王强  35.0  开发工程师      NaN
3    刘洋  45.0     设计  75000.0
4    张伟  25.0     经理  70000.0
5  None  30.0     经理  85000.0
6    陈敏   NaN    设计师  72000.0
7    赵磊  55.0   None  90000.0
8    杨杰  60.0     开发      NaN

（2）数据清洗与整理步骤

In [64]:
# 1）检测缺失数据
missing_data = df.isna().sum()
print("缺失数据统计:\n", missing_data)

缺失数据统计:
 姓名    1
年龄    2
职位    1
工资    2
dtype: int64

In [65]:
# 2）处理缺失数据
df.dropna(subset=['姓名'], inplace=True)  # 删除姓名缺失的行
df['年龄'] = df['年龄'].fillna(df['年龄'].mean())  # 填充年龄缺失值为均值
df.dropna(subset=['工资'], inplace=True)  # 删除工资缺失的行
print("处理缺失数据后：")
print(df)

处理缺失数据后：
   姓名         年龄    职位       工资
0  张伟  25.000000    经理  70000.0
1  李娜  40.833333    开发  80000.0
3  刘洋  45.000000    设计  75000.0
4  张伟  25.000000    经理  70000.0
6  陈敏  40.833333   设计师  72000.0
7  赵磊  55.000000  None  90000.0

In [66]:
# 3）处理重复数据
df.drop_duplicates(inplace=True)
print("处理重复数据后：")
print(df)

处理重复数据后：
   姓名         年龄    职位       工资
0  张伟  25.000000    经理  70000.0
1  李娜  40.833333    开发  80000.0
3  刘洋  45.000000    设计  75000.0
6  陈敏  40.833333   设计师  72000.0
7  赵磊  55.000000  None  90000.0

In [67]:
# 4）规范化职位格式
position_mapping = {
    '经理': '经理',
    '设计': '设计师',
    '设计师': '设计师',
    '开发': '开发工程师',
    '开发工程师': '开发工程师'
}
df['职位'] = df['职位'].map(position_mapping)
print("规范化职位格式后：")
print(df)

规范化职位格式后：
   姓名         年龄     职位       工资
0  张伟  25.000000     经理  70000.0
1  李娜  40.833333  开发工程师  80000.0
3  刘洋  45.000000    设计师  75000.0
6  陈敏  40.833333    设计师  72000.0
7  赵磊  55.000000    NaN  90000.0

（3）最终数据检查

In [68]:
print("清洗后的数据集:\n", df)
print("数据类型:\n", df.dtypes)

清洗后的数据集:
    姓名         年龄     职位       工资
0  张伟  25.000000     经理  70000.0
1  李娜  40.833333  开发工程师  80000.0
3  刘洋  45.000000    设计师  75000.0
6  陈敏  40.833333    设计师  72000.0
7  赵磊  55.000000    NaN  90000.0
数据类型:
 姓名     object
年龄    float64
职位     object
工资    float64
dtype: object